CREATE TABLE  "EMPLOYEE_IMAGES" 
   (	"IMG_ID" NUMBER(6,0) NOT NULL ENABLE, 
	"EMPLOYEE_ID" NUMBER(6,0) NOT NULL ENABLE, 
	"IMAGE" BLOB, 
	"DESCRIPTION" VARCHAR2(100), 
	 CONSTRAINT "EMPLOYEE_IMAGES_PK" PRIMARY KEY ("IMG_ID") ENABLE
   )
/

